# Generated by Django 5.0.6 on 2024-05-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='disc',
            field=models.CharField(max_length=300),
        ),
    ]
